### ISSUE TITLE
About RGB/NIR dataset 

### ISSUE THREAD

**Issue by dengxiongshi** [RM-Zhang/SCPNet#4]
@RM-Zhang Hello, have the train/test dataset about the RGB/NIR.

**Comment by RM-Zhang** [comment]
Hello, please download the RGB/NIR dataset from https://www.epfl.ch/labs/ivrl/research/downloads/rgb-nir-scene-dataset/.
The training and test sets are randomly split. More details can be found in the supplementary material in this repo (docs/SCPNet-supp.pdf).

**Comment by dengxiongshi** [comment]
Thank you.
